# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: dolphinnext-cageseq-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0.0
  - samtools=1.3
  - ucsc-wigToBigWig=377
  - bedtools=2.29.2
  - star=2.6.1d # don't upgrade me - 2.7X indices incompatible with iGenomes.
  - macs2=2.2.7
  - numpy=1.23.1
